jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone the repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Run lint
      run: ./gradlew lint
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload lint results
      uses: actions/upload-artifact@v3
      with:
        path: ./app/build/reports/lint-results-debug.html
name: Lint
on:
  repository_dispatch:
    types: trigger-ga___lint.yml
