jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone the repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Run tests
      run: ./gradlew test
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: unitTestResults
        path: ./app/build/reports/tests/testDebugUnitTest/
name: Tests
on:
  repository_dispatch:
    types: trigger-ga___tests.yml
